# Generated by Django 4.2 on 2023-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_alter_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='categories',
            field=models.ManyToManyField(related_name='bikes', to='bike.category'),
        ),
    ]
