# Generated by Django 4.2 on 2023-04-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bike_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='categories',
        ),
    ]
