# Generated by Django 4.2 on 2023-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_remove_bike_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
