# Generated by Django 4.2 on 2023-05-02 03:56

import bike.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('paid_on', models.DateTimeField(blank=True, null=True, verbose_name='paid on')),
                ('due_date', models.DateTimeField(default=bike.models.invoice_due_to, verbose_name='due date')),
                ('amount', models.DecimalField(decimal_places=2, default=50, max_digits=6, validators=[bike.models.validate_positive_number])),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='UNPAID', max_length=32, verbose_name='status')),
                ('paid_via', models.TextField(default='Stripe')),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
