# Generated by Django 4.1.5 on 2023-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0015_alter_bikestatus_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
