#!/bin/sh
#
#

case "$1" in
  start)
	printf "Creating /dev/net/tun: "
	mkdir -p /dev/net
	mknod /dev/net/tun c 10 200
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Removing /dev/net: "
	rm /dev/net -R
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

