version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=specify_your_root_password
      - MARIADB_DATABASE=bike
      - MARIADB_USER=bike
      - MARIADB_PASSWORD=specify_your_password_for_bike

  web:
    build: .
    # command:
    #   - /bin/sh
    #   - '-c'
    #   - '/scripts/entrypoint.sh'
    #command: python manage.py runserver 0.0.0.0:8000
    command: 
        - /bin/sh 
        - -c 
        - |
                cron
                python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - ./Bike_Res:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
     - db
    security_opt:
      - label=type:container_runtime_t
