# Generated by Django 4.1 on 2023-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bike_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='categories',
        ),
        migrations.AddField(
            model_name='bike',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
