# Generated by Django 4.1.3 on 2023-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_user_credit_alter_bike_description_alter_bike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
