# Generated by Django 4.1.5 on 2023-06-08 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('track', models.IntegerField()),
                ('climb', models.FloatField()),
                ('time', models.DateTimeField()),
                ('error_horizontal', models.FloatField()),
                ('error_vertical', models.FloatField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bike.bike')),
            ],
        ),
    ]
