# Generated by Django 4.1.5 on 2023-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
