# Generated by Django 4.1.5 on 2023-06-10 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0011_bike_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.bike')),
            ],
        ),
    ]
