# Generated by Django 4.1.5 on 2023-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0014_reservation_use_store_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikestatus',
            name='is_locked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
